kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-begrens-innsyn
  namespace: default
  labels:
    team: eessipensjon
spec:
  env:
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: SRVUSERNAME
      value: srveessi-pensjon-b
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: VIRKSOMHET_PERSON_V3_SECURITYTOKEN
      value: SAML
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: https://wasapp-q2.adeo.no/tpsws/ws/Person/v3
    - name: VIRKSOMHET_PERSON_V3_WSDLURL
      value: http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-person-v3-tjenestespesifikasjon/3.6.1/nav-person-v3-tjenestespesifikasjon-3.6.1.zip
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q2.preprod.local/SecurityTokenServiceProvider/
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-q2.nais.preprod.local/cpi
    - name: EESSIFAGMODULSERVICE_URL
      value: https://eessi-fagmodul-q2.nais.preprod.local/
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-begrens-innsyn.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 4096Mi
    requests:
      cpu: 400m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srveessi-pensjon-b
        mountPath: /var/run/secrets/nais.io/srveessi-pensjon-begrens-innsyn
      - kvPath: /kv/preprod/fss/eessi-pensjon-begrens-innsyn/default
        mountPath: /var/run/secrets/nais.io/vault
