kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-begrens-innsyn
  namespace: q1
  labels:
    team: eessipensjon
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-q1.nais.preprod.local/cpi
    - name: EESSIFAGMODULSERVICE_URL
      value: https://eessi-pensjon-fagmodul-q1.nais.preprod.local/
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessi-basis-sedSendt-v1-q1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1-q1
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-begrens-innsyn-q1.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 4096Mi
    requests:
      cpu: 400m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{serviceuserkv}}
        mountPath: /var/run/secrets/nais.io/srveessi-pensjon-begrens-innsyn
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault