kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-begrens-innsyn-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: begrens-innsyn # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
    accessPolicy:
      outbound:
        external:
          - host: https://eessi-pensjon-begrens-innsyn-q1.dev.intern.nav.no
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: https://app-q1.adeo.no/tpsws-aura/ws/Person/v3
    - name: PDL_URL
      value: https://pdl-api-q1.dev-fss-pub.nais.io/graphql
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-q1.dev-fss-pub.nais.io/cpi
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-fss.eessibasis.eux-rina-api-q1
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss:pdl:pdl-api-q1
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessi-basis-sedSendt-v1-q1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1-q1
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-begrens-innsyn-q1.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 4096Mi
    requests:
      cpu: 400m
      memory: 1024Mi
