kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-begrens-innsyn-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  secureLogs:
    enabled: true
  envFrom:
    - secret: begrens-innsyn #srveessi-pensjon-b-4 value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: eux-rina-api-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-eessibasis.dev-fss-pub.nais.io/cpi
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-fss.eessibasis.eux-rina-api-q2
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1-q2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1-q2
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-begrens-innsyn-q2.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
