kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-begrens-innsyn
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: begrens-innsyn
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: https://eessi-pensjon-begrens-innsyn.intern.nav.no
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: https://app.adeo.no/tpsws-aura/ws/Person/v3
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api.prod-fss-pub.nais.io/cpi
    - name: AZURE_APP_EUX_CLIENT_ID
      value: prod-fss.eessibasis.eux-rina-api
    - name: AZURE_APP_PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-begrens-innsyn.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 4096Mi
    requests:
      cpu: 400m
      memory: 1024Mi
