@startuml
!pragma graphviz_dot smetana

package "Setup" {
    [Application] <<no.nav.eessi.pensjon>>
    [Health] <<..health..>>
}

[Begrens Innsyn] <<..begrens.innsyn..>> as begrensinnsyn

[Application] ~~> begrensinnsyn :uses

[Metrics] <<..metrics..>>

package "Support" {
    [Config] <<..config..>>
    [Security] <<..security..>>
    [Logging] <<..logging..>>

    [Security] --> [Metrics]
    [Security] -> [Logging]
    [Config] --> [Metrics]
}

[Config] --> [Security]
[Config] --> [Logging]

package "Services" {
  [UTILS] <<..utils..>>

  [Person] <<..personoppslag..>>
  [Person]  --> [Metrics]
  [Person]  --> [Logging]
  [Person]  --> [Security]

  [EUX] <<..eux..>>
  [EUX] -> [Metrics]
  [EUX] -> [Logging]
  [EUX] -> [Security]
  [EUX] -> [UTILS]


}

begrensinnsyn --> [EUX]
begrensinnsyn --> [Person]
begrensinnsyn -> [Metrics]
begrensinnsyn -> [Config]



@enduml
