name: Build, push, and deploy

on:
  push:
    branches:
      - feature/nyTagRutine
jobs:
  tag_build_and_deploy:
    name: 'Build, push, and deploy'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # LAGER VERSJONSNUMMER
      - name: 'Create version number'
        run: |
          export TZ=CET
          echo "::set-env name=DATE::$(date "+%Y-%m-%d-%H:%M:%S")"
          echo "::set-env name=COMMIT_HASH::$(git rev-parse HEAD)"

      # OPPRETTER IMAGE VARIABEL MED VERSJONSNUMMER
      - name: 'Set Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ env.DATE }}-${{ env.COMMIT_HASH }}"

      # BYGGER DOCKER CONTAINER
      - name: 'Build and publish Docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew -Pgithub clean build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.DISPATCH_TOKEN }}
          docker push ${{ env.IMAGE }}

      # OPPRETTER GIT TAG
      - name: 'Bump version and push tag'
        run: |
          git tag -a ${{ env.DATE }}-${{ env.COMMIT_HASH }} -m "${{ env.DATE }}-${{ env.COMMIT_HASH }}"
          git push