name: Build, push, and deploy

on:
  push:
    branches:
      - feature/nyTagRutine
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo og setter variable'
        run: |
         export TZ=CET
         git clone https://github.com/navikt/eessi-pensjon-begrens-innsyn.git
         cd eessi-pensjon-begrens-innsyn
         echo "::set-env name=DATE::$(date "+%Y-%m-%d--%H-%M-%S")"
         echo "::set-env name=COMMIT_HASH::$(git rev-parse HEAD)"

      # OPPRETTER IMAGE VARIABEL
      - name: 'Set Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ env.DATE }}---${{ env.COMMIT_HASH }}"

      # BYGGER DOCKER CONTAINER
      - name: 'Build and publish Docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd eessi-pensjon-begrens-innsyn
          ./gradlew -Pgithub clean build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.DISPATCH_TOKEN }}
          docker push ${{ env.IMAGE }}

      # LAGER VERSJONSNUMMER
      - name: 'Create version number'
        run: |
          curl -v -s -X POST https://api.github.com/repos/navikt/eessi-pensjon-begrens-innsyn/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'