name: Slash command dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Slash command dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          commands: prodsett
          repository: navikt/eessi-pensjon-begrens-innsyn