name: Manuell deploy
on:
  repository_dispatch:
    types: [prodsett-command]

jobs:
  deploy_manuelt:
    name: 'Manuell deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v2
      - name: 'Opprett nais variable'
        run: |
          echo "versjon: ${{ github.event.client_payload.slash_command.arg1 }}"
          echo "cluster: ${{ github.event.client_payload.slash_command.arg2 }}"
          echo "resource: nais/${{ github.event.client_payload.slash_command.arg2 }}.yml"
          echo "image: ghcr.io/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ github.event.client_payload.slash_command.arg1 }}"
      - name: 'Deploy to NAIS'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ github.event.client_payload.slash_command.arg2 }}
          RESOURCE: nais/${{ github.event.client_payload.slash_command.arg2 }}.yml
          IMAGE: ghcr.io/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ github.event.client_payload.slash_command.arg1 }}