name: Build, push, and deploy
on:
  repository_dispatch:
    types: [prodsett-command]

jobs:
  deploy_manuelt:
    name: 'Build, push, and deploy'
    runs-on: ubuntu-latest
    steps:
      # LOGGER VARIABLE
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - run: |
          echo "cluster: dev-fss"
          echo "resource: dev-fss-q2.yml"
          echo "vars: dev-fss-q2.json"
          echo "image: docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ github.event.client_payload.slash_command.arg1 }}"

      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - run: git fetch --prune
      # DEPLOYER TIL NAIS
      - name: 'Deploy to NAIS'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: dev-fss-q2.yml
          VARS: dev-fss-q2.json
          IMAGE: docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ github.event.client_payload.slash_command.arg1 }}"