#name: Build, push, and deploy
#
#on:
#  repository_dispatch:
#    types: [prodsett-command]
#
#jobs:
#  deploy_manuelt:
#    name: 'Build, push, and deploy'
#    runs-on: ubuntu-latest
#    steps:
#      # DEPLOYER TIL NAIS
#      - name: 'Deploy to NAIS'
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-fss
#          RESOURCE: nais-q2.yml
#          VARS: dev-fss-q2.json
#          IMAGE: ${{ env.IMAGE }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: example-command
on:
repository_dispatch:
  types: [prodsett-command]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray